### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by patrickdronk** [orlandovald/webflux-twitter-demo#1]
Hi, 

I wanted to use your example but it's not working anymore.
this is the error logged by spring:
tailable cursor requested on non capped collection' on server localhost:27017

**Comment by orlandovald** [comment]
In order to support a tailable cursor (in order to read records as they come) in a Mongodb collection you need to create it with the capped attribute set to true, just create the collection manually with something similar to the below command inside the mongo shell (delete the collection if it's already created), 

`db.createCollection("tweets", {capped:true, max:1500, size:1000000})`

That should make that error go away, let me know otherwise.
